/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package model;

/**
 *
 * @author mathieu_canzerini
 */
public enum Grade {

    CEINTURE_BLANCHE,
    CEINTURE_BLANCHE_JAUNE,
    CEINTURE_JAUNE,
    CEINTURE_JAUNE_ORANGE,
    CEINTURE_ORANGE,
    CEINTURE_ORANGE_VERTE,
    CEINTURE_VERTE,
    CEINTURE_VERTE_BLEUE,
    CEINTURE_BLEUE,
    CEINTURE_BLEUE_MARRON,
    CEINTURE_MARRON,
    CEINTURE_NOIRE_TECHNIQUE,
    CEINTURE_NOIRE_PREMIERE_DAN_TECHNIQUE,
    CEINTURE_NOIRE_PREMIERE_DAN,
    CEINTURE_NOIRE_DEUXIEME_DAN_TECHNIQUE,
    CEINTURE_NOIRE_DEUXIEME_DAN,
    CEINTURE_NOIRE_TROISIEME_DAN_TECHNIQUE,
    CEINTURE_NOIRE_TROISIEME_DAN,
    CEINTURE_NOIRE_QUATRIEME_DAN_TECHNIQUE,
    CEINTURE_NOIRE_QUATRIEME_DAN,
    CEINTURE_NOIRE_CINQUIEME_DAN_TECHNIQUE,
    CEINTURE_NOIRE_CINQUIEME_DAN,
    CEINTURE_NOIRE_SIXIEME_DAN_TECHNIQUE,
    CEINTURE_NOIRE_SIXIEME_DAN,
    CEINTURE_NOIRE_SEPTIEME_DAN_TECHNIQUE,
    CEINTURE_NOIRE_SEPTIEME_DAN,
    CEINTURE_NOIRE_HUITIEME_DAN_TECHNIQUE,
    CEINTURE_NOIRE_HUITIEME_DAN,
    CEINTURE_NOIRE_NEUVIEME_DAN_TECHNIQUE,
    CEINTURE_NOIRE_NEUVIEME_DAN,
    CEINTURE_NOIRE_DIXIEME_DAN_TECHNIQUE,
    CEINTURE_NOIRE_DIXIEME_DAN;
}
