INSERT INTO Evenement(id_evenement, date_evenement, nom_evenement, photo_principale) VALUES (4,'2012-11-18', 'Coupe Départementale Kumité', 'defaut_evenement.jpg');
INSERT INTO Competition(id_evenement) VALUES (4);
INSERT INTO Evenement(id_evenement, date_evenement, nom_evenement, photo_principale) VALUES (5,'2012-11-18', 'Championnat Départemental Kumité', 'defaut_evenement.jpg');
INSERT INTO Competition(id_evenement) VALUES (5);
INSERT INTO Evenement(id_evenement, date_evenement, nom_evenement, photo_principale) VALUES (6,'2013-01-26', 'Coupe de Lorraine Kumité', 'defaut_evenement.jpg');
INSERT INTO Competition(id_evenement) VALUES (6);
INSERT INTO Evenement(id_evenement, date_evenement, nom_evenement, photo_principale) VALUES (7,'2013-02-10', 'Championnat de Lorraine Kumité Senior', 'defaut_evenement.jpg');
INSERT INTO Competition(id_evenement) VALUES (7);
INSERT INTO Evenement(id_evenement, date_evenement, nom_evenement, photo_principale) VALUES (8,'2013-02-17', 'Championnat de Lorraine Kumité', 'defaut_evenement.jpg');
INSERT INTO Competition(id_evenement) VALUES (8);
INSERT INTO Evenement(id_evenement, date_evenement, nom_evenement, photo_principale) VALUES (9,'2013-02-10', 'Coupe de Lorraine Corporative Kata', 'defaut_evenement.jpg');
INSERT INTO Competition(id_evenement) VALUES (9);
INSERT INTO Evenement(id_evenement, date_evenement, nom_evenement, photo_principale) VALUES (10,'2013-02-10', 'Coupe de Lorraine Corporative Kumité', 'defaut_evenement.jpg');
INSERT INTO Competition(id_evenement) VALUES (10);
INSERT INTO Evenement(id_evenement, date_evenement, nom_evenement, photo_principale) VALUES (11,'2013-01-13', 'Coupe Départementale Kata', 'defaut_evenement.jpg');
INSERT INTO Competition(id_evenement) VALUES (11);
INSERT INTO Evenement(id_evenement, date_evenement, nom_evenement, photo_principale) VALUES (12,'2013-01-27', 'Coupe Lorraine Kata', 'defaut_evenement.jpg');
INSERT INTO Competition(id_evenement) VALUES (12);
INSERT INTO Evenement(id_evenement, date_evenement, nom_evenement, photo_principale) VALUES (13,'2013-01-27', 'Championnat Lorraine Kata', 'defaut_evenement.jpg');
INSERT INTO Competition(id_evenement) VALUES (13);
INSERT INTO Evenement(id_evenement, date_evenement, nom_evenement, photo_principale) VALUES (14,'2013-01-13', 'Championnat Départemental Kumité Espoirs', 'defaut_evenement.jpg');
INSERT INTO Competition(id_evenement) VALUES (14);
INSERT INTO Evenement(id_evenement, date_evenement, nom_evenement, photo_principale) VALUES (15,'2012-10-20', "Open d'Arlon", 'defaut_evenement.jpg');
INSERT INTO Competition(id_evenement) VALUES (15);
INSERT INTO Evenement(id_evenement, date_evenement, nom_evenement, photo_principale) VALUES (16,'2012-11-11', "Coupe de France Kumité Cadet", 'defaut_evenement.jpg');
INSERT INTO Competition(id_evenement) VALUES (16);
INSERT INTO Evenement(id_evenement, date_evenement, nom_evenement, photo_principale) VALUES (17,'2012-10-13', "Open ADIDAS", 'defaut_evenement.jpg');
INSERT INTO Competition(id_evenement) VALUES (17);
INSERT INTO Evenement(id_evenement, date_evenement, nom_evenement, photo_principale) VALUES (18,'2013-02-10', 'Championnat de Lorraine Kumité Senior Open', 'defaut_evenement.jpg');
INSERT INTO Competition(id_evenement) VALUES (18);
INSERT INTO Evenement(id_evenement, date_evenement, nom_evenement, photo_principale) VALUES (19,'2013-01-13', 'Championnat Départemental Kata', 'defaut_evenement.jpg');
INSERT INTO Competition(id_evenement) VALUES (19);

INSERT INTO Personne(nom_personne, prenom_personne, sexe) VALUES ('BELLOCCO','Alessio','MASCULIN');
INSERT INTO Licencie(id_personne) VALUES (13);
INSERT INTO Personne(nom_personne, prenom_personne, sexe) VALUES ('CAPELLE','Baptiste','MASCULIN');
INSERT INTO Licencie(id_personne) VALUES (15);
INSERT INTO Personne(nom_personne, prenom_personne, sexe) VALUES ('CAPELLE','Nathan','MASCULIN');
INSERT INTO Licencie(id_personne) VALUES (16);
INSERT INTO Personne(nom_personne, prenom_personne, sexe) VALUES ('CHENOT','Clément','MASCULIN');
INSERT INTO Licencie(id_personne) VALUES (17);
INSERT INTO Personne(nom_personne, prenom_personne, sexe) VALUES ('DE RIBEIRO','Anthony','MASCULIN');
INSERT INTO Licencie(id_personne) VALUES (18);
INSERT INTO Personne(nom_personne, prenom_personne, sexe) VALUES ('DI CESARE','Adrien','MASCULIN');
INSERT INTO Licencie(id_personne) VALUES (19);
INSERT INTO Personne(nom_personne, prenom_personne, sexe) VALUES ('GRESSANI','Julie','FEMININ');
INSERT INTO Licencie(id_personne) VALUES (20);
INSERT INTO Personne(nom_personne, prenom_personne, sexe) VALUES ('GRESSANI','Mathieu','MASCULIN');
INSERT INTO Licencie(id_personne) VALUES (21);
INSERT INTO Personne(nom_personne, prenom_personne, sexe) VALUES ('GRUN','Amélie','FEMININ');
INSERT INTO Licencie(id_personne) VALUES (22);
INSERT INTO Personne(nom_personne, prenom_personne, sexe) VALUES ('GUGLIELMI','Jonathan','MASCULIN');
INSERT INTO Licencie(id_personne) VALUES (23);
INSERT INTO Personne(nom_personne, prenom_personne, sexe) VALUES ('JUVAN','Lucille','FEMININ');
INSERT INTO Licencie(id_personne) VALUES (24);
INSERT INTO Personne(nom_personne, prenom_personne, sexe) VALUES ('JUVAN','Noémie','FEMININ');
INSERT INTO Licencie(id_personne) VALUES (25);
INSERT INTO Personne(nom_personne, prenom_personne, sexe) VALUES ('KABAT','Maxime','MASCULIN');
INSERT INTO Licencie(id_personne) VALUES (26);
INSERT INTO Personne(nom_personne, prenom_personne, sexe) VALUES ('KACI','Eva','FEMININ');
INSERT INTO Licencie(id_personne) VALUES (27);
INSERT INTO Personne(nom_personne, prenom_personne, sexe) VALUES ('LARUE','Mylène','FEMININ');
INSERT INTO Licencie(id_personne) VALUES (28);
INSERT INTO Personne(nom_personne, prenom_personne, sexe) VALUES ('LEISEN','Eric','MASCULIN');
INSERT INTO Licencie(id_personne) VALUES (29);
INSERT INTO Personne(nom_personne, prenom_personne, sexe) VALUES ('LORBER','Eléonore','FEMININ');
INSERT INTO Licencie(id_personne) VALUES (30);
INSERT INTO Personne(nom_personne, prenom_personne, sexe) VALUES ('MANCINI','Emma','FEMININ');
INSERT INTO Licencie(id_personne) VALUES (31);
INSERT INTO Personne(nom_personne, prenom_personne, sexe) VALUES ('MANCINI','Jonathan','MASCULIN');
INSERT INTO Licencie(id_personne) VALUES (32);
INSERT INTO Personne(nom_personne, prenom_personne, sexe) VALUES ('MAZZONETTO','Enzo','MASCULIN');
INSERT INTO Licencie(id_personne) VALUES (33);
INSERT INTO Personne(nom_personne, prenom_personne, sexe) VALUES ('MORICONI','Caroline','FEMININ');
INSERT INTO Licencie(id_personne) VALUES (34);
INSERT INTO Personne(nom_personne, prenom_personne, sexe) VALUES ('MULLER','Guillaume','MASCULIN');
INSERT INTO Licencie(id_personne) VALUES (35);
INSERT INTO Personne(nom_personne, prenom_personne, sexe) VALUES ('MULLER','Laurine','FEMININ');
INSERT INTO Licencie(id_personne) VALUES (36);
INSERT INTO Personne(nom_personne, prenom_personne, sexe) VALUES ('OSCENDA','Aymeric','MASCULIN');
INSERT INTO Licencie(id_personne) VALUES (37);
INSERT INTO Personne(nom_personne, prenom_personne, sexe) VALUES ('PARADISI','Claude','MASCULIN');
INSERT INTO Licencie(id_personne) VALUES (38);
INSERT INTO Personne(nom_personne, prenom_personne, sexe) VALUES ('PERFETTO','Jonathan','MASCULIN');
INSERT INTO Licencie(id_personne) VALUES (39);
INSERT INTO Personne(nom_personne, prenom_personne, sexe) VALUES ('PERFETTO','Raphaël','MASCULIN');
INSERT INTO Licencie(id_personne) VALUES (40);
INSERT INTO Personne(nom_personne, prenom_personne, sexe) VALUES ('SCALIA','Lisa','FEMININ');
INSERT INTO Licencie(id_personne) VALUES (41);
INSERT INTO Personne(nom_personne, prenom_personne, sexe) VALUES ('SCHMITT','Sabrina','FEMININ');
INSERT INTO Licencie(id_personne) VALUES (42);
INSERT INTO Personne(nom_personne, prenom_personne, sexe) VALUES ('SOAVI','Guillaume','MASCULIN');
INSERT INTO Licencie(id_personne) VALUES (43);
INSERT INTO Personne(nom_personne, prenom_personne, sexe) VALUES ('TESTA','Maéna','FEMININ');
INSERT INTO Licencie(id_personne) VALUES (44);
INSERT INTO Personne(nom_personne, prenom_personne, sexe) VALUES ('TURCHINI','Sébastien','MASCULIN');
INSERT INTO Licencie(id_personne) VALUES (45);
INSERT INTO Personne(nom_personne, prenom_personne, sexe) VALUES ('VIDON','Hugo','MASCULIN');
INSERT INTO Licencie(id_personne) VALUES (46);
INSERT INTO Personne(nom_personne, prenom_personne, sexe) VALUES ('VIDON','Johan','MASCULIN');
INSERT INTO Licencie(id_personne) VALUES (47);
INSERT INTO Personne(nom_personne, prenom_personne, sexe) VALUES ('VOLL','Chloé','FEMININ');
INSERT INTO Licencie(id_personne) VALUES (48);
INSERT INTO Personne(nom_personne, prenom_personne, sexe) VALUES ('VOLL','Stéphanie','MASCULIN');
INSERT INTO Licencie(id_personne) VALUES (49);

INSERT INTO Resultat(place_resultat,id_competition, id_licencie) VALUES (3, 4, 13);
INSERT INTO Resultat(place_resultat,id_competition, id_licencie) VALUES (3, 6, 13);
INSERT INTO Resultat(place_resultat,id_competition, id_licencie) VALUES (2, 9, 13);
INSERT INTO Resultat(place_resultat,id_competition, id_licencie) VALUES (1, 5, 12);
INSERT INTO Resultat(place_resultat,id_competition, id_licencie) VALUES (1, 7, 12);
INSERT INTO Resultat(place_resultat,id_competition, id_licencie) VALUES (1, 4, 15);
INSERT INTO Resultat(place_resultat,id_competition, id_licencie) VALUES (3, 6, 15);
INSERT INTO Resultat(place_resultat,id_competition, id_licencie) VALUES (3, 11, 15);
INSERT INTO Resultat(place_resultat,id_competition, id_licencie) VALUES (1, 12, 15);
INSERT INTO Resultat(place_resultat,id_competition, id_licencie) VALUES (1, 9, 16);
INSERT INTO Resultat(place_resultat,id_competition, id_licencie) VALUES (2, 10, 16);
INSERT INTO Resultat(place_resultat,id_competition, id_licencie) VALUES (3, 19, 16);
INSERT INTO Resultat(place_resultat,id_competition, id_licencie) VALUES (3, 13, 16);
INSERT INTO Resultat(place_resultat,id_competition, id_licencie) VALUES (1, 15, 16);
INSERT INTO Resultat(place_resultat,id_competition, id_licencie) VALUES (1, 5, 17);
INSERT INTO Resultat(place_resultat,id_competition, id_licencie) VALUES (1, 10, 17);
INSERT INTO Resultat(place_resultat,id_competition, id_licencie) VALUES (3, 16, 17);
INSERT INTO Resultat(place_resultat,id_competition, id_licencie) VALUES (2, 5, 18);
INSERT INTO Resultat(place_resultat,id_competition, id_licencie) VALUES (2, 5, 19);
INSERT INTO Resultat(place_resultat,id_competition, id_licencie) VALUES (2, 9, 19);
INSERT INTO Resultat(place_resultat,id_competition, id_licencie) VALUES (3, 10, 19);
INSERT INTO Resultat(place_resultat,id_competition, id_licencie) VALUES (2, 19, 19);
INSERT INTO Resultat(place_resultat,id_competition, id_licencie) VALUES (3, 13, 19);
INSERT INTO Resultat(place_resultat,id_competition, id_licencie) VALUES (3, 11, 20);
INSERT INTO Resultat(place_resultat,id_competition, id_licencie) VALUES (2, 12, 20);
INSERT INTO Resultat(place_resultat,id_competition, id_licencie) VALUES (3, 5, 21);
INSERT INTO Resultat(place_resultat,id_competition, id_licencie) VALUES (1, 9, 21);
INSERT INTO Resultat(place_resultat,id_competition, id_licencie) VALUES (1, 10, 21);
INSERT INTO Resultat(place_resultat,id_competition, id_licencie) VALUES (3, 19, 21);
INSERT INTO Resultat(place_resultat,id_competition, id_licencie) VALUES (3, 13, 21);
INSERT INTO Resultat(place_resultat,id_competition, id_licencie) VALUES (1, 4, 22);
INSERT INTO Resultat(place_resultat,id_competition, id_licencie) VALUES (1, 6, 22);
INSERT INTO Resultat(place_resultat,id_competition, id_licencie) VALUES (3, 19, 23);
INSERT INTO Resultat(place_resultat,id_competition, id_licencie) VALUES (1, 13, 23);
INSERT INTO Resultat(place_resultat,id_competition, id_licencie) VALUES (1, 15, 23);
INSERT INTO Resultat(place_resultat,id_competition, id_licencie) VALUES (2, 4, 24);
INSERT INTO Resultat(place_resultat,id_competition, id_licencie) VALUES (1, 11, 24);
INSERT INTO Resultat(place_resultat,id_competition, id_licencie) VALUES (2, 12, 24);
INSERT INTO Resultat(place_resultat,id_competition, id_licencie) VALUES (1, 4, 25);
INSERT INTO Resultat(place_resultat,id_competition, id_licencie) VALUES (1, 12, 25);
INSERT INTO Resultat(place_resultat,id_competition, id_licencie) VALUES (3, 5, 26);
INSERT INTO Resultat(place_resultat,id_competition, id_licencie) VALUES (1, 14, 26);
INSERT INTO Resultat(place_resultat,id_competition, id_licencie) VALUES (3, 4, 27);
INSERT INTO Resultat(place_resultat,id_competition, id_licencie) VALUES (3, 6, 27);
INSERT INTO Resultat(place_resultat,id_competition, id_licencie) VALUES (1, 10, 28);
INSERT INTO Resultat(place_resultat,id_competition, id_licencie) VALUES (3, 10, 29);
INSERT INTO Resultat(place_resultat,id_competition, id_licencie) VALUES (2, 5, 30);
INSERT INTO Resultat(place_resultat,id_competition, id_licencie) VALUES (1, 10, 30);
INSERT INTO Resultat(place_resultat,id_competition, id_licencie) VALUES (1, 4, 31);
INSERT INTO Resultat(place_resultat,id_competition, id_licencie) VALUES (3, 11, 31);
INSERT INTO Resultat(place_resultat,id_competition, id_licencie) VALUES (2, 4, 32);
INSERT INTO Resultat(place_resultat,id_competition, id_licencie) VALUES (2, 4, 33);
INSERT INTO Resultat(place_resultat,id_competition, id_licencie) VALUES (2, 4, 34);
INSERT INTO Resultat(place_resultat,id_competition, id_licencie) VALUES (3, 6, 34);
INSERT INTO Resultat(place_resultat,id_competition, id_licencie) VALUES (3, 11, 34);
INSERT INTO Resultat(place_resultat,id_competition, id_licencie) VALUES (1, 12, 34);
INSERT INTO Resultat(place_resultat,id_competition, id_licencie) VALUES (3, 5, 35);
INSERT INTO Resultat(place_resultat,id_competition, id_licencie) VALUES (1, 4, 36);
INSERT INTO Resultat(place_resultat,id_competition, id_licencie) VALUES (2, 6, 36);
INSERT INTO Resultat(place_resultat,id_competition, id_licencie) VALUES (1, 5, 37);
INSERT INTO Resultat(place_resultat,id_competition, id_licencie) VALUES (3, 17, 37);
INSERT INTO Resultat(place_resultat,id_competition, id_licencie) VALUES (1, 9, 38);
INSERT INTO Resultat(place_resultat,id_competition, id_licencie) VALUES (3, 10, 39);
INSERT INTO Resultat(place_resultat,id_competition, id_licencie) VALUES (1, 10, 40);
INSERT INTO Resultat(place_resultat,id_competition, id_licencie) VALUES (2, 5, 41);
INSERT INTO Resultat(place_resultat,id_competition, id_licencie) VALUES (2, 19, 41);
INSERT INTO Resultat(place_resultat,id_competition, id_licencie) VALUES (1, 13, 41);
INSERT INTO Resultat(place_resultat,id_competition, id_licencie) VALUES (3, 4, 42);
INSERT INTO Resultat(place_resultat,id_competition, id_licencie) VALUES (2, 11, 43);
INSERT INTO Resultat(place_resultat,id_competition, id_licencie) VALUES (2, 4, 44);
INSERT INTO Resultat(place_resultat,id_competition, id_licencie) VALUES (3, 11, 44);
INSERT INTO Resultat(place_resultat,id_competition, id_licencie) VALUES (2, 9, 45);
INSERT INTO Resultat(place_resultat,id_competition, id_licencie) VALUES (2, 10, 45);
INSERT INTO Resultat(place_resultat,id_competition, id_licencie) VALUES (1, 9, 46);
INSERT INTO Resultat(place_resultat,id_competition, id_licencie) VALUES (1, 11, 46);
INSERT INTO Resultat(place_resultat,id_competition, id_licencie) VALUES (3, 12, 46);
INSERT INTO Resultat(place_resultat,id_competition, id_licencie) VALUES (3, 5, 47);
INSERT INTO Resultat(place_resultat,id_competition, id_licencie) VALUES (2, 10, 47);
INSERT INTO Resultat(place_resultat,id_competition, id_licencie) VALUES (2, 4, 48);
INSERT INTO Resultat(place_resultat,id_competition, id_licencie) VALUES (3, 5, 49);
INSERT INTO Resultat(place_resultat,id_competition, id_licencie) VALUES (3, 10, 49);
INSERT INTO Resultat(place_resultat,id_competition, id_licencie) VALUES (3, 18, 49);

